Imports System
Imports System.Runtime.InteropServices

<ComImport(), Guid("00000114-0000-0000-C000-000000000046"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)> _
Public Interface IOleWindow
    <PreserveSig()> _
    Function GetWindow(<Out()> ByRef phwnd As IntPtr) As Integer
    <PreserveSig()> _
    Function ContextSensitiveHelp(<[In](), MarshalAs(UnmanagedType.Bool)> ByVal fEnterMode As Boolean) As Integer
End Interface

Public Enum OLECMDEXECOPT
    OLECMDEXECOPT_DODEFAULT
    OLECMDEXECOPT_PROMPTUSER
    OLECMDEXECOPT_DONTPROMPTUSER
    OLECMDEXECOPT_SHOWHELP
End Enum

Public Enum OLECMDF
    OLECMDF_DEFHIDEONCTXTMENU = &H20
    OLECMDF_ENABLED = 2
    OLECMDF_INVISIBLE = &H10
    OLECMDF_LATCHED = 4
    OLECMDF_NINCHED = 8
    OLECMDF_SUPPORTED = 1
End Enum

Public Enum OLECMDID
    OLECMDID_ALLOWUILESSSAVEAS = &H2E
    OLECMDID_CLEARSELECTION = &H12
    OLECMDID_CLOSE = &H2D
    OLECMDID_COPY = 12
    OLECMDID_CUT = 11
    OLECMDID_DELETE = &H21
    OLECMDID_DONTDOWNLOADCSS = &H2F
    OLECMDID_ENABLE_INTERACTION = &H24
    OLECMDID_FIND = &H20
    OLECMDID_FOCUSVIEWCONTROLS = &H39
    OLECMDID_FOCUSVIEWCONTROLSQUERY = &H3A
    OLECMDID_GETPRINTTEMPLATE = &H34
    OLECMDID_GETZOOMRANGE = 20
    OLECMDID_HIDETOOLBARS = &H18
    OLECMDID_HTTPEQUIV = &H22
    OLECMDID_HTTPEQUIV_DONE = &H23
    OLECMDID_NEW = 2
    OLECMDID_ONTOOLBARACTIVATED = &H1F
    OLECMDID_ONUNLOAD = &H25
    OLECMDID_OPEN = 1
    OLECMDID_PAGEACTIONBLOCKED = &H37
    OLECMDID_PAGEACTIONUIQUERY = &H38
    OLECMDID_PAGESETUP = 8
    OLECMDID_PASTE = 13
    OLECMDID_PASTESPECIAL = 14
    OLECMDID_PREREFRESH = &H27
    OLECMDID_PRINT = 6
    OLECMDID_PRINT2 = &H31
    OLECMDID_PRINTPREVIEW = 7
    OLECMDID_PRINTPREVIEW2 = 50
    OLECMDID_PROPERTIES = 10
    OLECMDID_PROPERTYBAG2 = &H26
    OLECMDID_REDO = &H10
    OLECMDID_REFRESH = &H16
    OLECMDID_SAVE = 3
    OLECMDID_SAVEAS = 4
    OLECMDID_SAVECOPYAS = 5
    OLECMDID_SELECTALL = &H11
    OLECMDID_SETDOWNLOADSTATE = &H1D
    OLECMDID_SETPRINTTEMPLATE = &H33
    OLECMDID_SETPROGRESSMAX = &H19
    OLECMDID_SETPROGRESSPOS = &H1A
    OLECMDID_SETPROGRESSTEXT = &H1B
    OLECMDID_SETTITLE = &H1C
    OLECMDID_SHOWFIND = &H2A
    OLECMDID_SHOWMESSAGE = &H29
    OLECMDID_SHOWPAGEACTIONMENU = &H3B
    OLECMDID_SHOWPAGESETUP = &H2B
    OLECMDID_SHOWPRINT = &H2C
    OLECMDID_SHOWSCRIPTERROR = 40
    OLECMDID_SPELL = 9
    OLECMDID_STOP = &H17
    OLECMDID_STOPDOWNLOAD = 30
    OLECMDID_UNDO = 15
    OLECMDID_UPDATECOMMANDS = &H15
    OLECMDID_UPDATEPAGESTATUS = &H30
    OLECMDID_ZOOM = &H13
End Enum

Public Enum tagREADYSTATE
    READYSTATE_UNINITIALIZED
    READYSTATE_LOADING
    READYSTATE_LOADED
    READYSTATE_INTERACTIVE
    READYSTATE_COMPLETE
End Enum
